<HTML>
<HEAD>
<TITLE>System.StackOverflowException Class</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF">
<H3>System.StackOverflowException Class</H3>

<BLOCKQUOTE>
<TABLE COLS="1" ROWS="1" WIDTH="100%">
<TR><TD BGCOLOR="#EEEEFF"><PRE>public sealed class StackOverflowException : SystemException</PRE></TD></TR>
</TABLE>
</BLOCKQUOTE>

<H4>Base Types</H4>

<BLOCKQUOTE>
<A HREF="Object.html" TARGET="contents">Object</A><BR>
&nbsp;&nbsp;<A HREF="Exception.html" TARGET="contents">Exception</A><BR>
&nbsp;&nbsp;&nbsp;&nbsp;<A HREF="SystemException.html" TARGET="contents">SystemException</A><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;StackOverflowException<P>

</BLOCKQUOTE>

<H4>Assembly</H4>

<BLOCKQUOTE>
mscorlib
</BLOCKQUOTE>

<H4>Summary</H4>

<BLOCKQUOTE>
 Represents the error that occurs when the execution stack overflows due to too many
      method calls.<P>

</BLOCKQUOTE>

<H4>Description</H4>

<BLOCKQUOTE>
[<I>Note</I>: <A HREF="StackOverflowException.html" TARGET="contents">StackOverflowException</A> is thrown for execution stack overflow errors, typically
      in the case of a very deep or unbounded recursion. <P>

The localloc IL instruction throws <A HREF="StackOverflowException.html" TARGET="contents">StackOverflowException</A>.<P>

]<P>

</BLOCKQUOTE>

<H4>Example</H4>

<BLOCKQUOTE>
The following example demonstrates an error that causes
      a <A HREF="StackOverflowException.html" TARGET="contents">StackOverflowException</A> exception.<P>

<PRE>using System;
public class StackOverflowExample {
   public static void recursion() { recursion(); }
   public static void Main() {
      try {
         recursion();
      }
      catch(StackOverflowException e) {
         Console.WriteLine(&quot;Error caught: {0}&quot;, e);
      }
   }
}
   </PRE>
The output is<P>

<CODE>Error 
      caught: System.StackOverflowException: Exception of type
      System.StackOverflowException was thrown.</CODE><P>

</BLOCKQUOTE>

<H4>See Also</H4>

<BLOCKQUOTE>
<A HREF="System.html" TARGET="members">System Namespace</A>
</BLOCKQUOTE>

<H4>Members</H4>

<BLOCKQUOTE>
<P>

StackOverflowException Constructors<P>

<A HREF="#StackOverflowException() Constructor" TARGET="contents">StackOverflowException() Constructor</A><BR>
<A HREF="#StackOverflowException(System.String) Constructor" TARGET="contents">StackOverflowException(System.String) Constructor</A><BR>
<A HREF="#StackOverflowException(System.String, System.Exception) Constructor" TARGET="contents">StackOverflowException(System.String, System.Exception) Constructor</A><BR>
</BLOCKQUOTE>

<HR>

<A NAME="StackOverflowException() Constructor"><H3>StackOverflowException() Constructor</H3>

<BLOCKQUOTE>
<TABLE COLS="1" ROWS="1" WIDTH="100%">
<TR><TD BGCOLOR="#EEEEFF"><PRE>public StackOverflowException();</PRE></TD></TR>
</TABLE>
</BLOCKQUOTE>

<H4>Summary</H4>

<BLOCKQUOTE>
Constructs and initializes a new instance of the <A HREF="StackOverflowException.html" TARGET="contents">StackOverflowException</A> class.<P>

</BLOCKQUOTE>

<H4>Description</H4>

<BLOCKQUOTE>
This constructor initializes the System.StackOverflowException.Message property of the new instance to a system-supplied
   message that describes the error, such as &quot;The requested operation caused a
   stack overflow.&quot; This message takes into account the current system culture.<P>

The System.StackOverflowException.InnerException property is initialized to 
<CODE>null</CODE>
.<P>

</BLOCKQUOTE>

<H4>See Also</H4>

<BLOCKQUOTE>
<A HREF="StackOverflowException.html" TARGET="contents">System.StackOverflowException Class</A>, <A HREF="System.html" TARGET="members">System Namespace</A>
</BLOCKQUOTE>

</A><HR>

<A NAME="StackOverflowException(System.String) Constructor"><H3>StackOverflowException(System.String) Constructor</H3>

<BLOCKQUOTE>
<TABLE COLS="1" ROWS="1" WIDTH="100%">
<TR><TD BGCOLOR="#EEEEFF"><PRE>public StackOverflowException(string message);</PRE></TD></TR>
</TABLE>
</BLOCKQUOTE>

<H4>Summary</H4>

<BLOCKQUOTE>
Constructs and initializes a new instance of the <A HREF="StackOverflowException.html" TARGET="contents">StackOverflowException</A>
class. <P>

</BLOCKQUOTE>

<H4>Parameters</H4>

<BLOCKQUOTE>
<DL>
<DT>message</DT>
<DD>A <A HREF="String.html" TARGET="contents">String</A> that describes the error. The content of <I>message</I> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</DD>
</DL>
</BLOCKQUOTE>

<H4>Description</H4>

<BLOCKQUOTE>
 This constructor initializes the System.StackOverflowException.Message property of the new instance using <I>message</I>. If <I>message</I> is 
<CODE>null</CODE>
, the System.StackOverflowException.Message property is initialized to the 
   system-supplied message provided by the constructor that takes no arguments. The System.StackOverflowException.InnerException property is initialized to <CODE>null</CODE>
.<P>

</BLOCKQUOTE>

<H4>See Also</H4>

<BLOCKQUOTE>
<A HREF="StackOverflowException.html" TARGET="contents">System.StackOverflowException Class</A>, <A HREF="System.html" TARGET="members">System Namespace</A>
</BLOCKQUOTE>

</A><HR>

<A NAME="StackOverflowException(System.String, System.Exception) Constructor"><H3>StackOverflowException(System.String, System.Exception) Constructor</H3>

<BLOCKQUOTE>
<TABLE COLS="1" ROWS="1" WIDTH="100%">
<TR><TD BGCOLOR="#EEEEFF"><PRE>public StackOverflowException(string message, Exception innerException);</PRE></TD></TR>
</TABLE>
</BLOCKQUOTE>

<H4>Summary</H4>

<BLOCKQUOTE>
Constructs and initializes a new instance of the <A HREF="StackOverflowException.html" TARGET="contents">StackOverflowException</A>
class.<P>

</BLOCKQUOTE>

<H4>Parameters</H4>

<BLOCKQUOTE>
<DL>
<DT>message</DT>
<DD>A <A HREF="String.html" TARGET="contents">String</A> that describes the error. The content of <I>message</I> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.</DD>
<DT>innerException</DT>
<DD>An instance of <A HREF="Exception.html" TARGET="contents">Exception</A> that is the cause of the current Exception. If <I>innerException</I> is non-null, then the current Exception was raised in a catch block handling <I>innerException</I> .</DD>
</DL>
</BLOCKQUOTE>

<H4>Description</H4>

<BLOCKQUOTE>
This constructor initializes the System.StackOverflowException.Message property of the new instance using <I>message</I>, and
   the System.StackOverflowException.InnerException property using
<I>innerException</I>. If <I>message</I> is 
<CODE>null</CODE>
, the System.StackOverflowException.Message property is initialized to the 
   system-supplied message provided by the constructor that takes no arguments.<P>

[<I>Note</I>: For information on inner exceptions, see
System.Exception.InnerException.]<P>

<P>

</BLOCKQUOTE>

<H4>See Also</H4>

<BLOCKQUOTE>
<A HREF="StackOverflowException.html" TARGET="contents">System.StackOverflowException Class</A>, <A HREF="System.html" TARGET="members">System Namespace</A>
</BLOCKQUOTE>

</A></BODY>
</HTML>
